/**
 * ALL text shown in the app lives here.
 * To add Hindi or Marathi later: create the same object in another file
 * (for example strings.hi.ts) and pick one in this file based on the language.
 */
export const strings = {
  appName: 'DukaanBill',
  rupee: '₹',

  common: {
    loading: 'Please wait...',
    retry: 'Try again',
    cancel: 'Cancel',
    delete: 'Delete',
    save: 'Save',
    saving: 'Saving...',
    done: 'Done',
    search: 'Search',
    optional: '(optional)',
    close: 'Close',
    errorTitle: 'Something went wrong',
    networkError: 'No internet. Please check your connection and try again.',
    unknownError: 'Something went wrong. Please try again.',
    noAccessTitle: 'Only for the owner',
    noAccessBody: 'You do not have permission to open this page.',
    goHome: 'Go to Home',
    notSetUpTitle: 'App is not set up yet',
    notSetUpBody:
      'The Supabase keys are missing. Copy .env.example to .env, add your keys, and restart the app.',
  },

  auth: {
    loginTitle: 'Welcome',
    loginSubtitle: 'Enter your mobile number. We will send you a code by SMS.',
    mobileLabel: 'Mobile number',
    mobilePlaceholder: '10 digit mobile number',
    sendCode: 'Send Code',
    sendingCode: 'Sending code...',
    verifyTitle: 'Enter the code',
    verifySubtitle: (phone: string) => `We sent a code to +91 ${phone}`,
    codeLabel: 'Code from SMS',
    codePlaceholder: '6 digit code',
    verify: 'Verify and Continue',
    verifying: 'Checking...',
    resend: 'Send code again',
    resendIn: (s: number) => `Send again in ${s} seconds`,
    changeNumber: 'Change mobile number',
    wrongCode: 'That code is not correct or has expired. Please try again.',
    codeSent: 'A new code was sent.',
    createShopTitle: 'Set up your shop',
    createShopSubtitle: 'Tell us about your shop. You can change this later.',
    shopNameLabel: 'Shop name',
    shopNamePlaceholder: 'Example: Sharma General Store',
    ownerNameLabel: 'Your name',
    ownerNamePlaceholder: 'Example: Ramesh Sharma',
    createShop: 'Create My Shop',
    creatingShop: 'Creating...',
    loggingIn: 'Opening your shop...',
    logout: 'Log out',
  },

  home: {
    title: 'Home',
    todaySales: "Today's sales",
    bills: (n: number) => (n === 1 ? '1 bill' : `${n} bills`),
    newBill: 'New Bill',
    products: 'Products',
    report: 'Report',
    history: 'Bill History',
    lowStock: 'Low Stock',
    lowStockCount: (n: number) => (n === 1 ? '1 item is low' : `${n} items are low`),
    stockOk: 'Stock is fine',
    settings: 'Settings',
    salesLoadError: "Could not load today's sales.",
  },

  products: {
    title: 'Products',
    searchPlaceholder: 'Search product name',
    add: 'Add Product',
    addTitle: 'Add Product',
    editTitle: 'Edit Product',
    emptyTitle: 'No products yet',
    emptyBodyOwner: 'Add your first product to start making bills.',
    emptyBodyStaff: 'The owner has not added any products yet.',
    noMatchTitle: 'No product found',
    noMatchBody: 'Try a different name.',
    nameLabel: 'Product name',
    namePlaceholder: 'Example: Sugar',
    priceLabel: 'Selling price (₹)',
    stockLabel: 'Stock quantity',
    unitLabel: 'Unit',
    lowLimitLabel: 'Tell me when stock is this low or less',
    lowLimitHint: 'You will see this product in the Low Stock list.',
    delete: 'Delete Product',
    deleteTitle: 'Delete this product?',
    deleteBody: (name: string) =>
      `${name} will be removed from your list. Old bills will not change.`,
    inStock: (qty: string, unit: string) => `${qty} ${unit} in stock`,
    lowBadge: 'Low',
    outBadge: 'Out of stock',
    notFound: 'This product was not found.',
  },

  bill: {
    newTitle: 'New Bill',
    addItems: 'Add Items',
    addMoreItems: 'Add More Items',
    pickerTitle: 'Pick products',
    pickerHint: 'Tap a product to add it to the bill.',
    noItemsTitle: 'No items yet',
    noItemsBody: 'Tap "Add Items" and pick what the customer is buying.',
    inBill: (n: number) => `${n} in bill`,
    remove: 'Remove',
    stockLeft: (qty: string, unit: string) => `${qty} ${unit} left`,
    notEnough: (qty: string, unit: string) => `Only ${qty} ${unit} in stock`,
    wholeOnly: 'Use a whole number for this item',
    invalidQty: 'Enter a quantity more than 0',
    discount: 'Discount',
    discountAmount: '₹ Amount',
    discountPercent: '% Percent',
    discountPlaceholder: 'Enter discount',
    discountTooBig: (max: string) => `Discount cannot be more than ${max} (the bill amount)`,
    percentTooBig: 'Percent must be 100 or less',
    customer: 'Customer',
    customerName: 'Customer name',
    customerPhone: 'Customer mobile number',
    payment: 'How did the customer pay?',
    cash: 'Cash',
    upi: 'UPI',
    udhaar: 'Udhaar',
    udhaarHelp: 'Udhaar means the customer will pay later. Name and mobile number are needed.',
    subtotal: 'Sub total',
    discountLine: 'Discount',
    total: 'Total',
    save: 'Save Bill',
    saving: 'Saving bill...',
    needItems: 'Please add at least one item.',
    fixErrors: 'Please fix the items marked in red.',
    saveFailed: 'The bill was not saved.',
    previewTitle: 'Bill',
    billNumber: (n: number) => `Bill No. ${n}`,
    whatsapp: 'Send on WhatsApp',
    sharePdf: 'Share PDF',
    makingPdf: 'Making PDF...',
    pdfFailed: 'Could not make the PDF. Please try again.',
    pdfNotAvailable: 'Sharing is not available on this phone.',
    whatsappFailed: 'Could not open WhatsApp. Is it installed?',
    anotherBill: 'Make Another Bill',
    notFound: 'This bill was not found.',
    thankYou: 'Thank you! Visit again.',
    gst: 'GSTIN',
    paidBy: 'Payment',
    date: 'Date',
    phone: 'Phone',
    item: 'Item',
    qty: 'Qty',
    rate: 'Rate',
    amount: 'Amount',
    customerLabel: 'Customer',
    udhaarNote: 'Amount is on Udhaar (pay later).',
  },

  history: {
    title: 'Bill History',
    emptyTitle: 'No bills yet',
    emptyBody: 'Bills you make will show up here.',
    loadMore: 'Show older bills',
    walkIn: 'Walk-in customer',
  },

  report: {
    title: 'Sales Report',
    total: 'Total sales',
    bills: 'Number of bills',
    cash: 'Cash',
    upi: 'UPI',
    udhaar: 'Udhaar',
    split: 'How customers paid',
    top: 'Top 5 selling products',
    topHint: 'Ranked by sales amount',
    noSales: 'No sales on this day',
    noSalesBody: 'Bills made on this day will be counted here.',
    today: 'Today',
    changeDate: 'Change Date',
    previousDay: 'Previous day',
    nextDay: 'Next day',
    soldQty: (q: string, unit: string) => `${q} ${unit} sold`,
  },

  lowStock: {
    title: 'Low Stock',
    emptyTitle: 'All good!',
    emptyBody: 'No product is running low right now.',
    hint: 'These products are running low. Buy more soon.',
  },

  settings: {
    title: 'Settings',
    shopSection: 'Shop details',
    shopName: 'Shop name',
    address: 'Address',
    addressPlaceholder: 'Shop address (shown on the bill)',
    phone: 'Shop phone number',
    gst: 'GST number',
    gstHint: 'Leave empty if you do not have one. It is shown on the bill.',
    save: 'Save Changes',
    saved: 'Shop details saved.',
    staff: 'Staff',
    staffSubtitle: 'Add or remove people who can make bills',
    logout: 'Log Out',
    logoutTitle: 'Log out?',
    logoutBody: 'You will need a new SMS code to log in again.',
    account: 'Logged in as',
    role: { owner: 'Owner', staff: 'Staff' },
  },

  staff: {
    title: 'Staff',
    addTitle: 'Add a staff member',
    addHelp:
      'Staff can make bills and see products. They log in with this mobile number using the same SMS code screen.',
    nameLabel: 'Staff name',
    phoneLabel: 'Staff mobile number',
    add: 'Add Staff',
    adding: 'Adding...',
    emptyTitle: 'No staff yet',
    emptyBody: 'Add a mobile number above so someone else can make bills.',
    pending: 'Has not logged in yet',
    active: 'Active',
    remove: 'Remove',
    removeTitle: 'Remove this person?',
    removeBody: (who: string) => `${who} will not be able to make bills any more.`,
    added: 'Staff added. Ask them to log in with this number.',
    alreadyAdded: 'This number is already added.',
    ownNumber: 'This is your own number.',
  },

  errors: {
    required: 'This is required',
    phone: 'Enter a 10 digit mobile number',
    otp: 'Enter the 6 digit code',
    price: 'Price must be more than 0',
    stock: 'Stock cannot be less than 0',
    lowLimit: 'Limit cannot be less than 0',
    number: 'Enter a valid number',
    whole: 'Use a whole number (no decimals)',
    gst: 'GST number looks wrong. It has 15 letters and numbers.',
    udhaarNeedsCustomer: 'Name and mobile number are needed for Udhaar',
    tooLong: 'This is too long',
  },
} as const;

export type Strings = typeof strings;
